server:
  port: 9999
spring:
  cloud:
    gateway:
      routes:
      - id: passenger-service
        uri: http://localhost:9090
        predicates:
        - Path=/passenger-service/**
      - id: accomodation-service
        uri: http://localhost:9091
        predicates:
        - Path=/accomodation-service/**